# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.contrib.postgres.fields
from django.conf import settings
import login.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('RollNo', models.PositiveIntegerField(serialize=False, primary_key=True, validators=[login.models.validate_Roll])),
                ('Name', models.CharField(max_length=80)),
                ('Current_Branch', models.CharField(default=b'', max_length=15, choices=[(b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Branch])),
                ('CPI', models.DecimalField(default=0.0, max_digits=4, decimal_places=2, validators=[login.models.validate_CPI])),
                ('Category', models.CharField(default=b'GE', max_length=4, choices=[(b'GE', b'GE'), (b'OBC', b'OBC'), (b'ST', b'ST'), (b'SC', b'SC')], validators=[login.models.validate_Category])),
                ('Preference1', models.CharField(default=b'null', max_length=15, choices=[(b'null', b'--'), (b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Preference])),
                ('Preference2', models.CharField(default=b'null', max_length=15, choices=[(b'null', b'--'), (b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Preference])),
                ('Preference3', models.CharField(default=b'null', max_length=15, choices=[(b'null', b'--'), (b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Preference])),
                ('Preference4', models.CharField(default=b'null', max_length=15, choices=[(b'null', b'--'), (b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Preference])),
                ('Preference5', models.CharField(default=b'null', max_length=15, choices=[(b'null', b'--'), (b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Preference])),
                ('Preference6', models.CharField(default=b'null', max_length=15, choices=[(b'null', b'--'), (b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Preference])),
                ('Preference7', models.CharField(default=b'null', max_length=15, choices=[(b'null', b'--'), (b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Preference])),
                ('Preference8', models.CharField(default=b'null', max_length=15, choices=[(b'null', b'--'), (b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Preference])),
                ('Preference9', models.CharField(default=b'null', max_length=15, choices=[(b'null', b'--'), (b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Preference])),
                ('Preference10', models.CharField(default=b'null', max_length=15, choices=[(b'null', b'--'), (b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Preference])),
                ('Preference11', models.CharField(default=b'null', max_length=15, choices=[(b'null', b'--'), (b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Preference])),
                ('Preference12', models.CharField(default=b'null', max_length=15, choices=[(b'null', b'--'), (b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Preference])),
                ('Preference13', models.CharField(default=b'null', max_length=15, choices=[(b'null', b'--'), (b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Preference])),
                ('Preference14', models.CharField(default=b'null', max_length=15, choices=[(b'null', b'--'), (b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Preference])),
                ('Preference15', models.CharField(default=b'null', max_length=15, choices=[(b'null', b'--'), (b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Preference])),
                ('PrefList', django.contrib.postgres.fields.ArrayField(null=True, base_field=models.CharField(default=b'null', max_length=15, choices=[(b'null', b'--'), (b'AE B.Tech', b'AE B.Tech'), (b'CE B.Tech', b'CE B.Tech'), (b'CH', b'CH'), (b'CL B.Tech', b'CL B.Tech'), (b'CL Dual Deg', b'CL Dual Deg'), (b'CS B.Tech', b'CS B.Tech'), (b'EE B.Tech', b'EE B.Tech'), (b'EE Dual Deg E1', b'EE Dual Deg E1'), (b'EE Dual Deg E2', b'EE Dual Deg E2'), (b'EN Dual Deg', b'EN Dual Deg'), (b'EP B.Tech', b'EP B.Tech'), (b'EP Dual Deg N1', b'EP Dual Deg N1'), (b'ME B.Tech', b'ME B.Tech'), (b'ME Dual Deg M2', b'ME Dual Deg M2'), (b'MM B.Tech', b'MM B.Tech'), (b'MM Dual Deg Y1', b'MM Dual Deg Y1'), (b'MM Dual Deg Y2', b'MM Dual Deg Y2')], validators=[login.models.validate_Preference]), size=17)),
                ('author', models.ForeignKey(default=b'', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
